name: 'GitHub Action for simctl'
description: 'A tool to interact with simctl on macOS agents'
author: "Simon Jarbrant <simonjarbrant@me.com>"
inputs:
  platform:
    description: 'The simulator platform (iOS, macOS, etc.)'
    required: false
  name:
    description: 'The name of the simulator'
    required: true
  os:
    description: 'OS version of the simulator'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
