name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm test

  # test action works running from the graph  
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        name: 'iPhone 8'
